
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Get environment variables with fallback values for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://enueigskmelglzbuuiqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudWVpZ3NrbWVsZ2x6YnV1aXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDU3MTIsImV4cCI6MjA1NzAyMTcxMn0.32UzHvqANLKKPMhelD15SSAyHWWnqbQ4wDYwOuSzNCY";

// Validate that we have the required configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check .env file or environment configuration.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
